### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by ahofmann4** [UBC-MDS/dsci_532_group23#16]
Hi Group 23,

I like your examples of the types of people who would use the app and why!

- Where will you put a legend for the map? 
- I wonder if your government official might like to be able to compare the data from their country with another country directly on a plot like the line plot at the bottom. Or be able to have their country’s values listed in the table/bar plot for comparison to the top countries. But maybe they would want to compare to countries most similar to their country (based on region or development level) to see what trends other countries in a similar situation have? Or to look at the values in the bar graph of a certain region.

**Comment by Tammy1128** [comment]
Thanks for your feedback! We will try our best to address these issues.
