### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by ahofmann4** [UBC-MDS/dsci_532_group23#26]
Hi Team 23,

- Overall well done implementing your dashboard plan! And thank you for the clear reflection. 
- I wish the per-capita values selection worked globally on all graph axis including your line plot. 
- I find changing the per-capita setting very striking. The data takes on very different meanings when switching between the two, and both views are useful.
- it’s too bad that the legend scale for the world map has to change for each energy type. I almost want a panel that shows me all the legends with labels so I can more easily compare and associate different colours between the different energy selections in the map. This I am not sure is a reasonable request in any way, I’m just musing here.
- using the slider wasn’t immediately intuitive. I thought I was selecting just one year, but it seems to be cumulative. A note either way would be helpful to clarify my confusion. Also, since I can click between years I’m assuming your data is collected by month, or half year? Do you want to have the user be able to select the range start and end? Right now the used can only select the end of the year range.
- x-axis label on the line plot would be good to add.
- On the topic of colour, there is quite a bit going on. One improvement would be to have all the colours across the dashboard match with the map legend, or to have the bar graph colours change according to the line-plot colours. This would just add some colour cohesion across the dashboard. I also think this is not necessarily something you would have to change.
- I also like how there are options to zoom in and out on the graphs, and the hover information for the map. A short caption below the map to let me know that I can hover to see the population size of each country would be helpful. Is there a reason not all countries can be hovered above for population info no matter the energy type selected?
- a title for the dashboard would be good to have.

**Comment by Tammy1128** [comment]
Thanks for your feedback! We will try our best to address these issues. Wish you all the best!
