### ISSUE TITLE
peer group feedback (group 22)

### ISSUE THREAD

**Issue by calsvein** [UBC-MDS/dsci_532_group23#27]
_**Hello group 23!**_

I’m a member of the public, and I’ve been hearing a lot about this thing called climate change. I wanted to learn what all the fuss is about, because my preconception is that everything is hunky-dorey. So I logged on to the World Energy Consumption App and… oh boy. As I look at the time series chart for the World, it looks like carbon fuel growth has been on a tear since 1980. It does look like coal usage has peaked, so that’s nice, but other fossil fuels march upwards. As a Canadian, this makes me wonder what our relative consumption path has been like. I select for Canada, and see that although Canada consumes almost no coal, that our growth has been steady for natural gas and petroleum. This makes me think that in fact, not all is well. That makes me angry, and now I channel that anger to be more green with my purchases. Hoorah! 

**The good:**

- we thought the layout looked nice (logical layout, good graph sizing ratios)
- we found it was easy to navigate and interact with the dashboard (intuitive)
- we thought your viz’s covered the types of comparisons people would want to logically make (country comparisons, a given countries usage over time, and filtering for top global users).
- we liked that the title of the map updated when you select a different year

**Areas to improve:**

- If possible, use a year slider that better gives the appearance that it is grabbing just one year (currently it looks like its a combined 1980 to selected year)
- If possible, have the tooltip for the map provide the full name of the country, rather than the acronym
- Some text describing what the app is, what BTU’s are, where the data was sourced.

**Comment by Tammy1128** [comment]
Thanks for your feedback! We will try our best to address these issues. Good luck on your projects
